# Generated by Django 5.2 on 2025-04-10 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VaccineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
            ],
        ),
        migrations.AddField(
            model_name='vaccine',
            name='age_group',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='approved_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='dose_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='dose_interval',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='status',
            field=models.CharField(choices=[('Active', 'Dang su dung'), ('Discontinued', 'Ngung su dung')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Ten Vaccine'),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='AppTiemChung.vaccinetype'),
        ),
    ]
