# Generated by Django 5.2 on 2025-05-13 12:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AppTiemChung', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='is_inoculated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='injectionsite',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1,
                                   null=True),
        ),
        migrations.AlterField(
            model_name='injectionsite',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('user', 'schedule')},
        ),
        migrations.AlterUniqueTogether(
            name='injectionschedule',
            unique_together={('vaccine', 'site', 'date')},
        ),
    ]
