# Generated by Django 5.2 on 2025-05-08 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='AppTiemChung.vaccinetype'),
        ),
    ]
