# Generated by Django 5.2 on 2025-04-10 03:40

import AppTiemChung.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0002_vaccinetype_vaccine_age_group_vaccine_approved_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='vaccine_type',
            field=models.ForeignKey(default=AppTiemChung.models.get_default_vaccine_type, on_delete=django.db.models.deletion.CASCADE, to='AppTiemChung.vaccinetype'),
        ),
    ]
