# Generated by Django 5.2 on 2025-05-13 12:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('AppTiemChung', '0002_appointment_is_inoculated_injectionsite_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='vaccinationrecord',
            unique_together={('user', 'vaccine', 'dose_number')},
        ),
    ]
