# Generated by Django 5.2 on 2025-05-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0003_alter_vaccinationrecord_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccinationrecord',
            name='health_note',
            field=models.TextField(default=None, null=True),
        ),
    ]
