# Generated by Django 5.2 on 2025-05-09 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AppTiemChung', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Nam'), ('F', 'Nữ'), ('O', 'Khác')], max_length=1,
                                   null=True),
        ),
    ]
