# Generated by Django 5.2 on 2025-04-10 04:00

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0003_alter_vaccine_vaccine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='citizen_id',
            field=models.CharField(default=0, max_length=12, unique=True, verbose_name='CCCD'),
        ),
    ]
