# Generated by Django 5.2 on 2025-04-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0004_user_avatar_user_citizen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccine',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinetype',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vaccinetype',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='vaccinetype',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
