# Generated by Django 5.2 on 2025-05-14 22:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AppTiemChung', '0004_vaccinationrecord_health_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='reminder_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
