# Generated by Django 5.2 on 2025-04-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0006_injectionsite_alter_vaccine_status_injectionschedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='dose_count',
            field=models.IntegerField(default=10000),
        ),
        migrations.AlterUniqueTogether(
            name='vaccine',
            unique_together={('name', 'vaccine_type')},
        ),
    ]
