# Generated by Django 5.2 on 2025-06-02 14:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('AppTiemChung', '0007_alter_chatmessage_sender'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
