# Generated by Django 5.2 on 2025-04-30 19:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0007_alter_vaccine_dose_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccine',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='vaccines'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
