# Generated by Django 5.2 on 2025-04-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0008_vaccine_image_alter_vaccine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
