# Generated by Django 5.2 on 2025-05-01 14:29

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0009_alter_vaccine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaccine',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
