# Generated by Django 5.2 on 2025-06-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AppTiemChung', '0009_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='is_user',
            field=models.BooleanField(default=True),
        ),
    ]
