# Generated by Django 5.2 on 2025-06-03 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('AppTiemChung', '0010_chatmessage_is_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='timestamp',
            field=models.DateTimeField(null=True),
        ),
    ]
