# Generated by Django 5.2 on 2025-05-03 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0011_alter_user_citizen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizen_id',
            field=models.CharField(default=None, max_length=12, unique=True, verbose_name='CCCD'),
        ),
    ]
