# Generated by Django 5.2 on 2025-05-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTiemChung', '0012_alter_user_citizen_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizen_id',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='CCCD'),
        ),
    ]
