# Generated by Django 5.2 on 2025-06-06 08:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('AppTiemChung', '0014_querylog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatMessage',
        ),
    ]
